<?php

namespace ContainerJ8707xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K7_I1DGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k7.I1DG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k7.I1DG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'retrait' => ['privates', '.errored..service_locator.k7.I1DG.App\\Entity\\Retraits', NULL, 'Cannot autowire service ".service_locator.k7.I1DG": it needs an instance of "App\\Entity\\Retraits" but this type has been excluded in "config/services.yaml".'],
        ], [
            'retrait' => 'App\\Entity\\Retraits',
        ]);
    }
}
