<?php

namespace ContainerJ8707xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QnySmo0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QnySmo0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QnySmo0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depot' => ['privates', '.errored..service_locator.QnySmo0.App\\Entity\\Depot', NULL, 'Cannot autowire service ".service_locator.QnySmo0": it needs an instance of "App\\Entity\\Depot" but this type has been excluded in "config/services.yaml".'],
            'depotRepository' => ['privates', 'App\\Repository\\DepotRepository', 'getDepotRepositoryService', true],
        ], [
            'depot' => 'App\\Entity\\Depot',
            'depotRepository' => 'App\\Repository\\DepotRepository',
        ]);
    }
}
