<?php

namespace ContainerJ8707xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M6XN6bgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m6XN6bg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m6XN6bg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientsRepository' => ['privates', 'App\\Repository\\ClientsRepository', 'getClientsRepositoryService', true],
        ], [
            'clientsRepository' => 'App\\Repository\\ClientsRepository',
        ]);
    }
}
