<?php

namespace ContainerJ8707xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3Gp0ZXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3Gp0_zX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3Gp0_zX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tontine' => ['privates', '.errored..service_locator.3Gp0_zX.App\\Entity\\Tontines', NULL, 'Cannot autowire service ".service_locator.3Gp0_zX": it needs an instance of "App\\Entity\\Tontines" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tontine' => 'App\\Entity\\Tontines',
        ]);
    }
}
