<?php

namespace ContainerJ8707xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SzWfT4EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.szWfT4E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.szWfT4E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', '.errored..service_locator.szWfT4E.App\\Entity\\Clients', NULL, 'Cannot autowire service ".service_locator.szWfT4E": it needs an instance of "App\\Entity\\Clients" but this type has been excluded in "config/services.yaml".'],
        ], [
            'client' => 'App\\Entity\\Clients',
        ]);
    }
}
