<?php

namespace ContainerJ8707xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0HBKrVo.App\Entity\Clients' shared service.
     *
     * @return \App\Entity\Clients
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0HBKrVo": it needs an instance of "App\\Entity\\Clients" but this type has been excluded in "config/services.yaml".');
    }
}
