<?php

namespace ContainerJ8707xH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTontines2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.L_Q9yMP.App\Entity\Tontines' shared service.
     *
     * @return \App\Entity\Tontines
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.L_Q9yMP": it needs an instance of "App\\Entity\\Tontines" but this type has been excluded in "config/services.yaml".');
    }
}
