<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Clients extends \App\Entity\Clients implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Mots_de_passe' => [parent::class, 'Mots_de_passe', null],
        "\0".parent::class."\0".'comptes' => [parent::class, 'comptes', null],
        "\0".parent::class."\0".'depots' => [parent::class, 'depots', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'prets' => [parent::class, 'prets', null],
        "\0".parent::class."\0".'profession' => [parent::class, 'profession', null],
        "\0".parent::class."\0".'remboursements' => [parent::class, 'remboursements', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        "\0".parent::class."\0".'tontines' => [parent::class, 'tontines', null],
        'Mots_de_passe' => [parent::class, 'Mots_de_passe', null],
        'comptes' => [parent::class, 'comptes', null],
        'depots' => [parent::class, 'depots', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'nom' => [parent::class, 'nom', null],
        'prenom' => [parent::class, 'prenom', null],
        'prets' => [parent::class, 'prets', null],
        'profession' => [parent::class, 'profession', null],
        'remboursements' => [parent::class, 'remboursements', null],
        'telephone' => [parent::class, 'telephone', null],
        'tontines' => [parent::class, 'tontines', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
