<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0HBKrVoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0HBKrVo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0HBKrVo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', '.errored..service_locator.0HBKrVo.App\\Entity\\Clients', NULL, 'Cannot autowire service ".service_locator.0HBKrVo": it needs an instance of "App\\Entity\\Clients" but this type has been excluded in "config/services.yaml".'],
            'clientsRepository' => ['privates', 'App\\Repository\\ClientsRepository', 'getClientsRepositoryService', true],
        ], [
            'client' => 'App\\Entity\\Clients',
            'clientsRepository' => 'App\\Repository\\ClientsRepository',
        ]);
    }
}
