<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4OEtC_0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4OEtC.0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4OEtC.0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'remboursementsRepository' => ['privates', 'App\\Repository\\RemboursementsRepository', 'getRemboursementsRepositoryService', true],
        ], [
            'remboursementsRepository' => 'App\\Repository\\RemboursementsRepository',
        ]);
    }
}
