<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5zVsKI2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5zVsKI2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5zVsKI2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pret' => ['privates', '.errored..service_locator.5zVsKI2.App\\Entity\\Pret', NULL, 'Cannot autowire service ".service_locator.5zVsKI2": it needs an instance of "App\\Entity\\Pret" but this type has been excluded in "config/services.yaml".'],
            'pretRepository' => ['privates', 'App\\Repository\\PretRepository', 'getPretRepositoryService', true],
        ], [
            'pret' => 'App\\Entity\\Pret',
            'pretRepository' => 'App\\Repository\\PretRepository',
        ]);
    }
}
