<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C9pW7V3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C9pW7V3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C9pW7V3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pretRepository' => ['privates', 'App\\Repository\\PretRepository', 'getPretRepositoryService', true],
        ], [
            'pretRepository' => 'App\\Repository\\PretRepository',
        ]);
    }
}
