<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JU1H3_SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JU1H3.S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JU1H3.S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'retraitsRepository' => ['privates', 'App\\Repository\\RetraitsRepository', 'getRetraitsRepositoryService', true],
        ], [
            'retraitsRepository' => 'App\\Repository\\RetraitsRepository',
        ]);
    }
}
