<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M027d3nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M027d3n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M027d3n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'retrait' => ['privates', '.errored..service_locator.M027d3n.App\\Entity\\Retraits', NULL, 'Cannot autowire service ".service_locator.M027d3n": it needs an instance of "App\\Entity\\Retraits" but this type has been excluded in "config/services.yaml".'],
            'retraitsRepository' => ['privates', 'App\\Repository\\RetraitsRepository', 'getRetraitsRepositoryService', true],
        ], [
            'retrait' => 'App\\Entity\\Retraits',
            'retraitsRepository' => 'App\\Repository\\RetraitsRepository',
        ]);
    }
}
