<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M97t1k2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m97t1k2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m97t1k2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compte' => ['privates', '.errored..service_locator.m97t1k2.App\\Entity\\Comptes', NULL, 'Cannot autowire service ".service_locator.m97t1k2": it needs an instance of "App\\Entity\\Comptes" but this type has been excluded in "config/services.yaml".'],
        ], [
            'compte' => 'App\\Entity\\Comptes',
        ]);
    }
}
