<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C88kg3zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C88kg3z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C88kg3z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'remboursement' => ['privates', '.errored..service_locator.C88kg3z.App\\Entity\\Remboursements', NULL, 'Cannot autowire service ".service_locator.C88kg3z": it needs an instance of "App\\Entity\\Remboursements" but this type has been excluded in "config/services.yaml".'],
        ], [
            'remboursement' => 'App\\Entity\\Remboursements',
        ]);
    }
}
