<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComptes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.m97t1k2.App\Entity\Comptes' shared service.
     *
     * @return \App\Entity\Comptes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.m97t1k2": it needs an instance of "App\\Entity\\Comptes" but this type has been excluded in "config/services.yaml".');
    }
}
