<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Qasi6tb.App\Entity\Depot' shared service.
     *
     * @return \App\Entity\Depot
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Qasi6tb": it needs an instance of "App\\Entity\\Depot" but this type has been excluded in "config/services.yaml".');
    }
}
