<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemboursementsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.C88kg3z.App\Entity\Remboursements' shared service.
     *
     * @return \App\Entity\Remboursements
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.C88kg3z": it needs an instance of "App\\Entity\\Remboursements" but this type has been excluded in "config/services.yaml".');
    }
}
