<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRetraits2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.k7.I1DG.App\Entity\Retraits' shared service.
     *
     * @return \App\Entity\Retraits
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.k7.I1DG": it needs an instance of "App\\Entity\\Retraits" but this type has been excluded in "config/services.yaml".');
    }
}
