<?php

namespace ContainerKEx5MwY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTontinesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3Gp0_zX.App\Entity\Tontines' shared service.
     *
     * @return \App\Entity\Tontines
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3Gp0_zX": it needs an instance of "App\\Entity\\Tontines" but this type has been excluded in "config/services.yaml".');
    }
}
