<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKEx5MwY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKEx5MwY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKEx5MwY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKEx5MwY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKEx5MwY\App_KernelDevDebugContainer([
    'container.build_hash' => 'KEx5MwY',
    'container.build_id' => '566df5a8',
    'container.build_time' => 1688109100,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKEx5MwY');
